### PR TITLE
Fix style by reverting HTML5 DOCTYPE

### PR DESCRIPTION
**Pull request by Rangi42**
image

### CODE REVIEW

**Comment by Rangi42** [comment]
Wow, it's been *decades* since I've had to think about the rendering [quirks](https://www.quirksmode.org/css/quirksmode.html) that not having a DOCTYPE makes the browser do.

**Comment by SelvinPL** [comment]
wait
```css
:root {
    --selectedfile-background: #ccf;
    --color: #2D2D2C;
    --background: #FAFAFA;
    --background-alt: #EFEFEF;
    --border-color: #D6D6D6;
    --log-info: #7D7D7C;
    --log-out: #1D1D1C;
    --log-err: #FF0000;
}

@media (prefers-color-scheme: dark) {
    :root {
        --selectedfile-background: #557;
        --color: #CCCCCC;
        --background: #2D2D2D;
        --background-alt: #424242;
        --border-color: #575757;
        --log-info: #999999;
        --log-out: #FFFFFF;
        --log-err: #FF0000;
    }
}

body {
    color: var(--color);
    background:var(--background);
}

input, textarea {
    border: 1px solid #555;
    border-radius: 4px;
    padding: 4px;
    background-color: var(--background);
    color: var(--color);
}

button {
    border: 1px solid #555;
    border-radius: 4px;
    padding: 8px;
    margin: 2px;
    background-color: var(--background);
    color: var(--color);
}

button:hover{
    background-color: var(--background-alt);
}

.cpuLineMarker {
  position:absolute;
  background:rgba(100,200,100,0.5);
  z-index:20
}
.ace_gutter-cell.ace_breakpoint{ 
    border-radius: 14px;
    box-shadow: 10px 0px 1px 1px #ff2020 inset; 
}
.ace_gutter-cell.ace_invalid_breakpoint{ 
    border-radius: 14px;
    box-shadow: 10px 0px 1px 1px #802020 inset; 
}
.right {
    text-align: right;
}

.tabs {
    display: flex;
    flex-wrap: wrap;
    border-bottom: 1px solid var(--border-color);
}
.tabs input[type=radio] {
    display: none;
}
.tabs label {
    border: 1px solid var(--border-color);
    background: var(--background-alt);
    padding: 4px 12px;
    border-radius: 4px 4px 0 0;
    position: relative;
    top: 1px;
}
.tabs input:checked + label {
    background: var(--background);
    border-bottom: 1px solid var(--background);
}
.tabs input + label + div {
    order: 99;
    display: none;
    flex-basis: 100%;
    padding: 16px;
    border-top: 1px solid var(--border-color);
    border-left: 1px solid var(--border-color);
    border-right: 1px solid var(--border-color);
}
.tabs input:checked + label + div {
    display: block;
}

table {
  border-collapse: collapse;
}
table, th, td {
  border: 1px solid var(--border-color);
  background: var(--background);
  font: 12px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
}
body {
  margin: 0;
}
textarea {
  resize: none;
}
canvas {
    image-rendering: pixelated;
}

.menubar {
  background: var(--background);
  border-bottom: 1px solid var(--border-color);
}
.menubar ul {
  padding: 0;
  margin: 0;
}
.menubar li {
  display: block;
  float: left;
  border: 1px solid var(--background-alt);
  padding: 0px 15px;
  position: relative;
  background-color: var(--background);
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
}

.menubar li ul {
  display: none;
  position: absolute;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 10;
}
.menubar li ul li {
  width: 100%;
}
.menubar ul li:hover {
  background-color: var(--background-alt);
}
.menubar li:hover ul, .menubar li:active ul {
  display: block;
}

.filelist ul {
  padding: 0;
  margin: 0;
}
.filelist li {
  overflow: auto;
  background: var(--background);
  font: 12px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
  padding: 1px;
  cursor: pointer;
  user-select: none;
}
.filelist li:nth-child(even) {background: var(--background-alt);}
.filelist li.active {background: var(--selectedfile-background)}
.filelist li.error {
    background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABOFBMVEX/////////QRswFAb/Ui4wFAYwFAYwFAaWGAfDRymzOSH/PxswFAb/SiUwFAYwFAbUPRvjQiDllog5HhHdRybsTi3/Tyv9Tir+Syj/UC3////XurebMBIwFAb/RSHbPx/gUzfdwL3kzMivKBAwFAbbvbnhPx66NhowFAYwFAaZJg8wFAaxKBDZurf/RB6mMxb/SCMwFAYwFAbxQB3+RB4wFAb/Qhy4Oh+4QifbNRcwFAYwFAYwFAb/QRzdNhgwFAYwFAbav7v/Uy7oaE68MBK5LxLewr/r2NXewLswFAaxJw4wFAbkPRy2PyYwFAaxKhLm1tMwFAazPiQwFAaUGAb/QBrfOx3bvrv/VC/maE4wFAbRPBq6MRO8Qynew8Dp2tjfwb0wFAbx6eju5+by6uns4uH9/f36+vr/GkHjAAAAYnRSTlMAGt+64rnWu/bo8eAA4InH3+DwoN7j4eLi4xP99Nfg4+b+/u9B/eDs1MD1mO7+4PHg2MXa347g7vDizMLN4eG+Pv7i5evs/v79yu7S3/DV7/498Yv24eH+4ufQ3Ozu/v7+y13sRqwAAADLSURBVHjaZc/XDsFgGIBhtDrshlitmk2IrbHFqL2pvXf/+78DPokj7+Fz9qpU/9UXJIlhmPaTaQ6QPaz0mm+5gwkgovcV6GZzd5JtCQwgsxoHOvJO15kleRLAnMgHFIESUEPmawB9ngmelTtipwwfASilxOLyiV5UVUyVAfbG0cCPHig+GBkzAENHS0AstVF6bacZIOzgLmxsHbt2OecNgJC83JERmePUYq8ARGkJx6XtFsdddBQgZE2nPR6CICZhawjA4Fb/chv+399kfR+MMMDGOQAAAABJRU5ErkJggg==");
    background-position: right;
    background-repeat: no-repeat;
}
.filelist li.warning {
    background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAmVBMVEX///8AAAD///8AAAAAAABPSzb/5sAAAAB/blH/73z/ulkAAAAAAAD85pkAAAAAAAACAgP/vGz/rkDerGbGrV7/pkQICAf////e0IsAAAD/oED/qTvhrnUAAAD/yHD/njcAAADuv2r/nz//oTj/p064oGf/zHAAAAA9Nir/tFIAAAD/tlTiuWf/tkIAAACynXEAAAAAAAAtIRW7zBpBAAAAM3RSTlMAABR1m7RXO8Ln31Z36zT+neXe5OzooRDfn+TZ4p3h2hTf4t3k3ucyrN1K5+Xaks52Sfs9CXgrAAAAjklEQVR42o3PbQ+CIBQFYEwboPhSYgoYunIqqLn6/z8uYdH8Vmdnu9vz4WwXgN/xTPRD2+sgOcZjsge/whXZgUaYYvT8QnuJaUrjrHUQreGczuEafQCO/SJTufTbroWsPgsllVhq3wJEk2jUSzX3CUEDJC84707djRc5MTAQxoLgupWRwW6UB5fS++NV8AbOZgnsC7BpEAAAAABJRU5ErkJggg==");
    background-position: right;
    background-repeat: no-repeat;
}

.modal {
    display: none;
    position: fixed;
    z-index: 100;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0,0.4);
}

.modal .content {
    background-color: var(--background);
    margin: 15% auto;
    padding: 20px;
    border: 1px solid var(--border);
    width: 80%;
}
.modal .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    cursor: pointer;
    user-select: none;
}
.modal .close:hover, .modal .close:focus {
    color: black;
}
.close {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAAE9JREFUeNpVzosJwCAMhGGX6GY1QEZwn4wQoDdlr/Ij9AA/kLzGNZ17zJ2Rcvpg24RUpqQwvZ40fpZRlD4qNp1wPimhgXaGMZpF/+2cxIEvFUVJj9IiGXQAAAAASUVORK5CYII=) no-repeat center;
    width: 24px;
    height: 24px;
}

.container {
    display: grid;
    grid-template-columns: 200px auto 520px;
    grid-template-rows: 21px auto 20%;
    grid-gap: 0;
    height: 98vh;
}
.menubar {
    grid-column: 1 / 4;
    grid-row: 1;
}
.sidebar {
    grid-column: 1;
    grid-row: 2;
    overflow: auto;
}
.editor {
    grid-column: 2;
    grid-row: 2;
}
.emulator {
    grid-column: 3;
    grid-row: 2 / 4;
}
.console {
    grid-column: 1 / 3;
    grid-row: 3;
}
.output {
    border: 1px inset #999;
    padding: 2px;
    width: calc(100% - 6px);
    height: calc(100% - 6px);
    overflow: auto;
}
.output .info {
    color: var(--log-info);
}
.output .stdout {
	color: var(--log-out);
}
.output .stderr {
    color: var(--log-err);
}

.emulator_screen_container {
    width: 512px;
    height: 512px;
}
.emulator_canvas_screen {
    width: 480px;
}
.emulator_vram_screen {
    width: 512px;
}

@media only screen and (max-height: 600px) {
    .emulator_screen_container {
        width: 256px;
        height: 256px;
    }
    .emulator_canvas_screen {
        width: 240px;
    }
    .emulator_vram_screen {
        width: 256px;
    }
}

@media only screen and (max-width: 600px) {
    .container {
        display: grid;
        grid-template-columns: auto;
        grid-template-rows: 22px 600px auto 100px 300px;
        grid-gap: 0;
    }
    .menubar {
        grid-column: 1;
        grid-row: 1;
    }
    .sidebar {
        grid-column: 1;
        grid-row: 4;
        overflow: auto;
    }
    .editor {
        grid-column: 1;
        grid-row: 2;
    }
    .emulator {
        grid-column: 1;
        grid-row: 3;
    }
    .console {
        grid-column: 1;
        grid-row: 5;
    }
}
```
fixes

**Comment by Rangi42** [comment]
Mind if we go with the simpler "revert the doctype I added for no particular reason" change? And then consider adding it back and making these deeper changes to how the layout works in non-quirks mode?

**Comment by SelvinPL** [comment]
Sure

**Pull request merged**
