### PR TITLE
Gist via querystring

### PR DESCRIPTION
**Pull request by SelvinPL**

### CODE REVIEW

**Comment by ISSOtm** [comment]
(Rebased after #37 was merged.)

**Review by ISSOtm — APPROVED** [review]
Looks about fine to me. Maybe the JS logic would “WTF” a more experienced Web dev, but I sure ain't one :)

**Comment by SelvinPL** [comment]
wait ... ther is already such functionalty via `#`

**Comment by SelvinPL** [comment]
do not merge this

**Comment by SelvinPL** [comment]
example

https://gbdev.io/rgbds-live/#https://gist.github.com/SelvinPL/acd390e5c5d5ead9e37de86f86a3f104

**Comment by ISSOtm** [comment]
Perhaps that's a little obscure, and should be documented somewhere? Or an option added in some menu?

**Comment by SelvinPL** [comment]
from menu it is also working File->Import Project... then GitHub Gist tab

**Comment by ISSOtm** [comment]
If there is a menu option, then I guess it should be sufficient. Thank you!

**Comment by SelvinPL** [comment]
I did add this before I fully(well not fully - I hate javascript and HTML and feel dirty making alll those changes) analyzed the code ... sorry for turmoil with this pull request

**Pull request closed without merging**
